### ISSUE TITLE
[Issue] No need to keep the selection popup open if max = 1

### ISSUE THREAD

**Issue by jestrella04** [lekoala/bootstrap5-tags#25]
On a recent enhancement request it was asked to keep the selection popup open when the multiple attribute is present on a select element. I found a small glitch on how the code was implemented: if multiple attribute is set but only one selection possible (max option set to 1) there's no need to keep displaying the popup since only one selection possible and it was already selected.

To replicate:

1. Set the multiple attribute on a select element.
2. Set the max option to 1, wither by data attributes or global options.
3. Load the website and select one option from the affected element.
4. The selection popup remains open but only one option is allowed.

A side effect issue of this, is that if you switch options from this dropdown a couple times, the popup will remain open no matter what, even if another popup is triggered from a different element.

**Comment by lekoala** [comment]
I've rework how single select work and I think it should fix it as well
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.8

**Comment by jestrella04** [comment]
For some strange reason 1.4.8 is breaking the implementation I have, been looking at it from a lot of different angles and still can't figure out why. And the end, downgrading to 1.4.7 fixes my issues so for sure there's something not playing well with the new version. I will keep looking at it and let you know the outcome.

PD: some of the issues I have is that the suggestions are not populated/displayed and placeholders are not displayed. In case this rings a bell for you.

**Comment by lekoala** [comment]
I made a couple of changes in this commit https://github.com/lekoala/bootstrap5-tags/commit/d3ed16599c62c122f4a5a3b0963174a3b9026aba
If you can try with the unminified lib and change back these lines and see what's wrong?

In the meantime i've published https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.9 that adds some more work on the single select that are a bit annoying to deal with

**Comment by jestrella04** [comment]
Looking good on the new version, also my previous problem seems to be gone as well. Closing this.
